### PR TITLE
Add version number

### PR DESCRIPTION
**Pull request by AlsoNiko**
Adds a version number to the releases, would require a new release to be set and an update to the json

### CODE REVIEW

**Comment by IMS212** [comment]
Concern

**Comment by TheNukeLore** [comment]
double concern

**Comment by ColdIce1605** [comment]
Triple concern

**Comment by Z-8Bit** [comment]
Omega concern

**Comment by maxigator** [comment]
Quintuple concern

**Comment by AlsoNiko** [comment]
Also bumps version number to 1.1.0

**Comment by IMS212** [comment]
do you mind rebasing/redoing as to fix the diff

**Pull request closed without merging**
